# Generated by Django 4.2.4 on 2023-09-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='tickers',
            field=models.ManyToManyField(to='common.ticker'),
        ),
    ]
