# Generated by Django 4.2.4 on 2023-08-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers_list', '0010_remove_ticker_index_alter_ticker_company_name'),
        ('stocks_portfolio', '0002_remove_portfolio_position_delete_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('price', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers_list.ticker')),
                ('to_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_portfolio.portfolio')),
            ],
        ),
    ]
