# Generated by Django 4.2.4 on 2023-08-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('stocks_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('price', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ticker')),
                ('to_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_portfolio.portfolio')),
            ],
        ),
    ]
