# Generated by Django 4.2.4 on 2023-08-23 16:13

from django.db import migrations, models
import django.db.models.deletion
import portfolio.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('stocks_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(validators=[portfolio.common.validators.min_share_count_validator])),
                ('price', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('avg_price', models.FloatField(default=0)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ticker')),
                ('to_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position')),
            ],
        ),
    ]
