# Generated by Django 4.2.4 on 2023-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
