# Generated by Django 4.2.4 on 2023-08-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_positionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionhistory',
            name='count',
        ),
        migrations.RemoveField(
            model_name='positionhistory',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='positionhistory',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='positionhistory',
            name='price',
        ),
    ]
