# Generated by Django 4.2.4 on 2023-08-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_alter_position_count_alter_position_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.FloatField(),
        ),
    ]
