# Generated by Django 4.2.4 on 2023-08-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_positionhistory_count_positionhistory_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionhistory',
            name='date_added',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
