# Generated by Django 4.2.4 on 2023-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0006_remove_positionhistory_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionhistory',
            name='info',
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
