# Generated by Django 4.2.4 on 2023-08-21 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_remove_positionhistory_info_positionhistory_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='count',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
