# Generated by Django 4.2.4 on 2023-08-21 19:59

from django.db import migrations, models
import portfolio.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0008_alter_position_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='avg_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='count',
            field=models.FloatField(validators=[portfolio.common.validators.min_share_count_validator]),
        ),
    ]
