# Generated by Django 4.2.4 on 2023-08-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_appuserhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuserhistory',
            old_name='user',
            new_name='to_user',
        ),
        migrations.AddField(
            model_name='appuserhistory',
            name='operation_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('dividend', 'Dividend')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuserhistory',
            name='ticker',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appuserhistory',
            name='count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
