# Generated by Django 4.2.4 on 2023-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='something',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
