# Generated by Django 4.2.4 on 2023-08-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_portfolio', '0002_portfolio_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='something',
        ),
    ]
