# Generated by Django 4.2.4 on 2023-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_portfolio', '0003_remove_portfolio_something'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
