# Generated by Django 4.2.4 on 2023-09-05 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_portfolio', '0004_alter_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cash',
            field=models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01)),
        ),
    ]
