# Generated by Django 4.2.4 on 2023-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='index',
            field=models.CharField(choices=[('S&P 500', 'sp500'), ('Dow Jones', 'dow'), ('Nasdaq', 'nasdaq')], max_length=9),
        ),
    ]
