# Generated by Django 4.2.4 on 2023-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers_list', '0002_alter_ticker_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='index',
        ),
        migrations.AddField(
            model_name='ticker',
            name='index',
            field=models.ManyToManyField(to='tickers_list.index'),
        ),
    ]
