# Generated by Django 4.2.4 on 2023-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers_list', '0003_index_remove_ticker_index_ticker_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='index',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.AddField(
            model_name='ticker',
            name='index',
            field=models.CharField(choices=[('S&P 500', 'sp500'), ('Dow Jones', 'dow'), ('Nasdaq 100', 'nasdaq')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
