# Generated by Django 4.2.4 on 2023-08-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers_list', '0004_remove_ticker_index_delete_index_ticker_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
