# Generated by Django 4.2.4 on 2023-08-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers_list', '0007_alter_ticker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
