# Generated by Django 4.2.4 on 2023-08-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers_list', '0008_alter_ticker_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='slug',
        ),
    ]
