# Generated by Django 4.2.4 on 2023-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers_list', '0009_remove_ticker_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='index',
        ),
        migrations.AlterField(
            model_name='ticker',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
